sudo: required
services:
  - docker

before_install:
  - docker build -t kevincepria/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kevincepria/react-test npm run test -- --coverage

after_success:
  - docker build -t kevincepria/multi-client ./client
  - docker build -t kevincepria/multi-nginx ./nginx
  - docker build -t kevincepria/multi-server ./server  
  - docker build -t kevincepria/multi-worker ./worker 
  #Login in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kevincepria/multi-client
  - docker push kevincepria/multi-nginx
  - docker push kevincepria/multi-server
  - docker push kevincepria/multi-worker

